import { PrismaClient, Category, Product } from '@prisma/client';

// Custom interfaces to handle potential Prisma Client sync issues in IDE
interface SeedCategory {
    id: string;
    label: string;
    labelHindi: string;
    emoji: string;
    description: string;
    gstRate: number;
}

const CATEGORIES: SeedCategory[] = [
    { id: 'cashew-sweets', label: 'Cashew Sweets', labelHindi: 'काजू मिठाई', emoji: '🥜', description: 'Premium sweets made with fine cashews.', gstRate: 5 },
    { id: 'ladoo', label: 'Ladoo', labelHindi: 'लड्डू', emoji: '🟡', description: 'Traditional round delights.', gstRate: 5 },
    { id: 'milk-sweets', label: 'Milk Sweets', labelHindi: 'दूध की मिठाई', emoji: '🥛', description: 'Rich fudge and milk-based desserts.', gstRate: 5 },
    { id: 'bengali-sweets', label: 'Bengali Sweets', labelHindi: 'बंगाली मिठाई', emoji: '⚪', description: 'Soft, spongy sweets soaked in syrup.', gstRate: 5 },
    { id: 'hot-fresh', label: 'Hot & Fresh', labelHindi: 'गरमा गरम', emoji: '🔥', description: 'Freshly prepared winter specials and jalebis.', gstRate: 5 },
    { id: 'savories', label: 'Savories', labelHindi: 'नमकीन', emoji: '🥨', description: 'Crispy, salty, and spicy snacks.', gstRate: 5 },
    { id: 'dry-fruits-ghee', label: 'Dry Fruits & Ghee', labelHindi: 'सूखे मेवे', emoji: '🥜', description: 'Flaky sweets rich in ghee and nuts.', gstRate: 5 },
    { id: 'cookies-bakery', label: 'Cookies & Bakery', labelHindi: 'कुकीज़ और बेकरी', emoji: '🍪', description: 'Freshly baked biscuits and cookies.', gstRate: 18 },
];

const PRODUCTS: any[] = [
    {
        id: '1',
        name: 'Kaju Katli',
        nameHindi: 'काजू कतली',
        slug: 'kaju-katli',
        description: 'Classic Indian sweet made with premium cashews, sugar, and silver leaf.',
        price: 900,
        originalPrice: null,
        categoryId: 'cashew-sweets',
        image: '/images/products/kaju-katli.png',
        rating: 4.9,
        reviewCount: 328,
        isVeg: true,
        isAvailable: true,
        isFeatured: true,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Cashews', 'Milk'],
        ingredients: null,
        shelfLifeDays: 15,
        badge: 'Bestseller',
        badgeColor: 'bg-saffron-500'
    },
    {
        id: '99',
        name: 'Atta Biscuits (Desi Ghee)',
        nameHindi: 'आटा बिस्कुट',
        slug: 'atta-biscuits',
        description: 'Crispy, traditional whole wheat biscuits baked fresh in pure desi ghee.',
        price: 250,
        originalPrice: null,
        categoryId: 'cookies-bakery',
        image: '/images/products/atta-biscuits.jpg',
        rating: 4.5,
        reviewCount: 89,
        isVeg: true,
        isAvailable: true,
        isFeatured: true,
        isTodaySpecial: false,
        weightGrams: 400,
        allergens: ['Gluten', 'Milk'],
        ingredients: null,
        shelfLifeDays: 30,
        badge: 'New',
        badgeColor: 'bg-blue-500'
    },
    {
        id: '2',
        name: 'Motichoor Ladoo',
        nameHindi: 'मोतीचूर लड्डू',
        slug: 'motichoor-ladoo',
        description: 'Tiny gram flour pearls fried in pure ghee and soaked in saffron syrup.',
        price: 600,
        originalPrice: null,
        categoryId: 'ladoo',
        image: '/images/products/motichoor-ladoo.png',
        rating: 4.8,
        reviewCount: 245,
        isVeg: true,
        isAvailable: true,
        isFeatured: true,
        isTodaySpecial: true,
        weightGrams: 500,
        allergens: ['Gluten', 'Milk', 'Nuts'],
        ingredients: null,
        shelfLifeDays: 7,
        badge: null,
        badgeColor: null
    },
    {
        id: '3',
        name: 'Milk Cake',
        nameHindi: 'मिल्क केक',
        slug: 'milk-cake',
        description: 'Traditional milk fudge made by slowly simmering milk and sugar.',
        price: 650,
        originalPrice: null,
        categoryId: 'milk-sweets',
        image: '/images/products/milk-cake.png',
        rating: 4.7,
        reviewCount: 189,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Milk'],
        ingredients: null,
        shelfLifeDays: 10,
        badge: null,
        badgeColor: null
    },
    {
        id: '4',
        name: 'Besan Ladoo',
        nameHindi: 'बेसन लड्डू',
        slug: 'besan-ladoo',
        description: 'Roasted gram flour roundelles made with desi ghee and premium nuts.',
        price: 550,
        originalPrice: null,
        categoryId: 'ladoo',
        image: '/images/products/besan-ladoo.png',
        rating: 4.6,
        reviewCount: 156,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Gluten', 'Nuts', 'Milk'],
        ingredients: null,
        shelfLifeDays: 20,
        badge: null,
        badgeColor: null
    },
    {
        id: '5',
        name: 'Gulab Jamun',
        nameHindi: 'गुलाब जामुन',
        slug: 'gulab-jamun',
        description: 'Soft, melt-in-mouth milk solids dumplings soaked in rose-flavored syrup.',
        price: 450,
        originalPrice: null,
        categoryId: 'milk-sweets',
        image: '/images/products/gulab-jamun.png',
        rating: 4.9,
        reviewCount: 412,
        isVeg: true,
        isAvailable: true,
        isFeatured: true,
        isTodaySpecial: true,
        weightGrams: 500,
        allergens: ['Milk', 'Gluten', 'Nuts'],
        ingredients: null,
        shelfLifeDays: 5,
        badge: 'Fresh Daily',
        badgeColor: 'bg-green-600'
    },
    {
        id: '6',
        name: 'Rasgulla',
        nameHindi: 'रसगुल्ला',
        slug: 'rasgulla',
        description: 'Spongy cottage cheese balls cooked in light sugar syrup.',
        price: 400,
        originalPrice: null,
        categoryId: 'bengali-sweets',
        image: '/images/products/rasgulla.png',
        rating: 4.8,
        reviewCount: 289,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Milk'],
        ingredients: null,
        shelfLifeDays: 3,
        badge: null,
        badgeColor: null
    },
    {
        id: '7',
        name: 'Desi Ghee Jalebi',
        nameHindi: 'देसी घी जलेबी',
        slug: 'desi-ghee-jalebi',
        description: 'Crispy, deep-fried spirals soaked in sugar syrup, made in pure desi ghee.',
        price: 450,
        originalPrice: null,
        categoryId: 'hot-fresh',
        image: '/images/products/jalebi.png',
        rating: 4.7,
        reviewCount: 315,
        isVeg: true,
        isAvailable: true,
        isFeatured: true,
        isTodaySpecial: true,
        weightGrams: 500,
        allergens: ['Gluten', 'Milk'],
        ingredients: null,
        shelfLifeDays: 2,
        badge: 'Hot item',
        badgeColor: 'bg-red-500'
    },
    {
        id: '8',
        name: 'Rasmalai',
        nameHindi: 'रसमलाई',
        slug: 'rasmalai',
        description: 'Soft cottage cheese discs soaked in sweetened, thickened milk with pistachios.',
        price: 500,
        originalPrice: null,
        categoryId: 'bengali-sweets',
        image: '/images/products/rasmalai.png',
        rating: 4.9,
        reviewCount: 378,
        isVeg: true,
        isAvailable: true,
        isFeatured: true,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Milk', 'Nuts'],
        ingredients: null,
        shelfLifeDays: 2,
        badge: null,
        badgeColor: null
    },
    {
        id: '9',
        name: 'Kaju Roll',
        nameHindi: 'काजू रोल',
        slug: 'kaju-roll',
        description: 'Premium cashew dough rolled with a core of crushed pistachios.',
        price: 1100,
        originalPrice: null,
        categoryId: 'cashew-sweets',
        image: '/images/products/kaju-roll.png',
        rating: 4.8,
        reviewCount: 142,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Cashews', 'Pistachios', 'Milk'],
        ingredients: null,
        shelfLifeDays: 15,
        badge: null,
        badgeColor: null
    },
    {
        id: '10',
        name: 'Namak Para',
        nameHindi: 'नमक पारा',
        slug: 'namak-para',
        description: 'Crispy savory squares flavored with carom seeds (ajwain).',
        price: 300,
        originalPrice: null,
        categoryId: 'savories',
        image: '/images/products/namak-para.png',
        rating: 4.5,
        reviewCount: 421,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Gluten'],
        ingredients: null,
        shelfLifeDays: 30,
        badge: null,
        badgeColor: null
    },
    {
        id: '11',
        name: 'Soan Papdi',
        nameHindi: 'सोन पापड़ी',
        slug: 'soan-papdi',
        description: 'Flaky, melt-in-the-mouth sweet made from gram flour and pure ghee.',
        price: 400,
        originalPrice: null,
        categoryId: 'dry-fruits-ghee',
        image: '/images/products/soan-papdi.png',
        rating: 4.6,
        reviewCount: 210,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Gluten', 'Nuts', 'Milk'],
        ingredients: null,
        shelfLifeDays: 45,
        badge: null,
        badgeColor: null
    },
    {
        id: '12',
        name: 'Moong Dal Halwa',
        nameHindi: 'मूंग दाल हलवा',
        slug: 'moong-dal-halwa',
        description: 'Rich and hearty winter sweet made from yellow lentils, ghee, and mixed nuts.',
        price: 700,
        originalPrice: null,
        categoryId: 'hot-fresh',
        image: '/images/products/moong-dal-halwa.png',
        rating: 4.9,
        reviewCount: 185,
        isVeg: true,
        isAvailable: true,
        isFeatured: true,
        isTodaySpecial: true,
        weightGrams: 500,
        allergens: ['Milk', 'Nuts'],
        ingredients: null,
        shelfLifeDays: 5,
        badge: 'Winter Special',
        badgeColor: 'bg-blue-600'
    },
    {
        id: '13',
        name: 'Boondi Ladoo',
        nameHindi: 'बूंदी लड्डू',
        slug: 'boondi-ladoo',
        description: 'Classic gram flour pearls fried in desi ghee, shaped into ladoos garnished with cashews and raisins.',
        price: 580,
        originalPrice: null,
        categoryId: 'ladoo',
        image: '/images/products/boondi-ladoo.png',
        rating: 4.7,
        reviewCount: 198,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Gluten', 'Milk', 'Nuts'],
        ingredients: null,
        shelfLifeDays: 10,
        badge: null,
        badgeColor: null
    },
    {
        id: '14',
        name: 'Doodh Peda',
        nameHindi: 'दूध पेड़ा',
        slug: 'doodh-peda',
        description: 'Melt-in-mouth milk fudge simmered with desi ghee and sugar to a rich, dense consistency.',
        price: 620,
        originalPrice: null,
        categoryId: 'milk-sweets',
        image: '/images/products/doodh-peda.png',
        rating: 4.8,
        reviewCount: 172,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Milk'],
        ingredients: null,
        shelfLifeDays: 10,
        badge: null,
        badgeColor: null
    },
    {
        id: '15',
        name: 'Pinni',
        nameHindi: 'पिन्नी',
        slug: 'pinni',
        description: 'Hearty Punjabi winter treat made with wheat flour, dry fruits, and generous desi ghee.',
        price: 650,
        originalPrice: null,
        categoryId: 'dry-fruits-ghee',
        image: '/images/products/pinni.png',
        rating: 4.7,
        reviewCount: 134,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Gluten', 'Nuts', 'Milk'],
        ingredients: null,
        shelfLifeDays: 20,
        badge: null,
        badgeColor: null
    },
    {
        id: '16',
        name: 'Gajar Ka Halwa',
        nameHindi: 'गाजर का हलवा',
        slug: 'gajar-ka-halwa',
        description: 'Winter favorite made with grated red carrots slow-cooked in milk, khoya, and pure desi ghee.',
        price: 650,
        originalPrice: null,
        categoryId: 'hot-fresh',
        image: '/images/products/gajar-halwa.png',
        rating: 4.9,
        reviewCount: 310,
        isVeg: true,
        isAvailable: true,
        isFeatured: true,
        isTodaySpecial: true,
        weightGrams: 500,
        allergens: ['Milk', 'Nuts'],
        ingredients: null,
        shelfLifeDays: 4,
        badge: 'Winter Special',
        badgeColor: 'bg-orange-500'
    },
    {
        id: '17',
        name: 'Sooji Halwa',
        nameHindi: 'सूजी हलवा',
        slug: 'sooji-halwa',
        description: 'Classic roasted semolina dessert cooked in desi ghee with sugar and cardamom.',
        price: 400,
        originalPrice: null,
        categoryId: 'hot-fresh',
        image: '/images/products/moong-dal-halwa.png',
        rating: 4.6,
        reviewCount: 221,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Gluten', 'Milk', 'Nuts'],
        ingredients: null,
        shelfLifeDays: 3,
        badge: null,
        badgeColor: null
    },
    {
        id: '18',
        name: 'Mysore Pak',
        nameHindi: 'मैसूर पाक',
        slug: 'mysore-pak',
        description: 'Famous South Indian sweet made from besan, sugar, and a generous pour of desi ghee — porous and melt-in-mouth.',
        price: 700,
        originalPrice: null,
        categoryId: 'dry-fruits-ghee',
        image: '/images/products/soan-papdi.png',
        rating: 4.8,
        reviewCount: 163,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Gluten', 'Milk'],
        ingredients: null,
        shelfLifeDays: 15,
        badge: null,
        badgeColor: null
    },
    {
        id: '19',
        name: 'Dodha Barfi',
        nameHindi: 'डोडा बर्फी',
        slug: 'dodha-barfi',
        description: 'Traditional Punjabi sweet made by caramelizing milk and wheat flour in desi ghee, loaded with crunchy nuts.',
        price: 750,
        originalPrice: null,
        categoryId: 'dry-fruits-ghee',
        image: '/images/products/milk-cake.png',
        rating: 4.8,
        reviewCount: 148,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Gluten', 'Milk', 'Nuts'],
        ingredients: null,
        shelfLifeDays: 20,
        badge: null,
        badgeColor: null
    },
    {
        id: '20',
        name: 'Patisa',
        nameHindi: 'पतीसा',
        slug: 'patisa',
        description: 'Golden, flaky North Indian sweet similar to soan papdi, made by layering gram flour with pure ghee.',
        price: 420,
        originalPrice: null,
        categoryId: 'dry-fruits-ghee',
        image: '/images/products/soan-papdi.png',
        rating: 4.5,
        reviewCount: 117,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Gluten', 'Milk'],
        ingredients: null,
        shelfLifeDays: 30,
        badge: null,
        badgeColor: null
    },
    {
        id: '21',
        name: 'Ghewar',
        nameHindi: 'घेवर',
        slug: 'ghewar',
        description: 'Honeycomb-shaped Rajasthani dessert made from flour batter fried in desi ghee and topped with rabri.',
        price: 550,
        originalPrice: null,
        categoryId: 'hot-fresh',
        image: '/images/products/soan-papdi.png',
        rating: 4.7,
        reviewCount: 139,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Gluten', 'Milk'],
        ingredients: null,
        shelfLifeDays: 2,
        badge: null,
        badgeColor: null
    },
    {
        id: '22',
        name: 'Imarti',
        nameHindi: 'इमरती',
        slug: 'imarti',
        description: 'Intricate lacy spirals of urad dal batter deep-fried in desi ghee and soaked in fragrant sugar syrup.',
        price: 480,
        originalPrice: null,
        categoryId: 'hot-fresh',
        image: '/images/products/jalebi.png',
        rating: 4.6,
        reviewCount: 124,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Gluten'],
        ingredients: null,
        shelfLifeDays: 2,
        badge: null,
        badgeColor: null
    },
    {
        id: '23',
        name: 'Balushahi',
        nameHindi: 'बालूशाही',
        slug: 'balushahi',
        description: 'Traditional doughnut-like sweet with a flaky, crumbly texture, fried in ghee and glazed with sugar.',
        price: 460,
        originalPrice: null,
        categoryId: 'dry-fruits-ghee',
        image: '/images/products/boondi-ladoo.png',
        rating: 4.6,
        reviewCount: 108,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 500,
        allergens: ['Gluten', 'Milk'],
        ingredients: null,
        shelfLifeDays: 15,
        badge: null,
        badgeColor: null
    },
    {
        id: '24',
        name: 'testing',
        nameHindi: 'टेस्टिंग',
        slug: 'testing',
        description: 'Test product for free delivery eligibility.',
        price: 1,
        originalPrice: null,
        categoryId: 'cashew-sweets',
        image: '/images/products/kaju-katli.png',
        rating: 5,
        reviewCount: 0,
        isVeg: true,
        isAvailable: true,
        isFeatured: false,
        isTodaySpecial: false,
        weightGrams: 100,
        allergens: [],
        ingredients: 'Sugar',
        shelfLifeDays: 7,
        badge: 'Free Delivery',
        badgeColor: 'green'
    },
];

const prisma = new PrismaClient();

async function main() {
    console.log('🌱 Starting database seed...');

    console.log('Seeding Categories...');
    for (const cat of CATEGORIES) {
        await prisma.category.upsert({
            where: { id: cat.id },
            update: {
                label: cat.label,
                labelHindi: cat.labelHindi,
                emoji: cat.emoji,
                description: cat.description,
                gstRate: cat.gstRate,
            } as any,
            create: {
                id: cat.id,
                label: cat.label,
                labelHindi: cat.labelHindi,
                emoji: cat.emoji,
                description: cat.description,
                gstRate: cat.gstRate,
            } as any, // Cast to any to bypass outdated Prisma client types in IDE
        });
    }
    console.log('Categories seeded.');

    console.log('Seeding Products...');
    for (const prod of PRODUCTS) {
        await prisma.product.upsert({
            where: { slug: prod.slug },
            update: {
                name: prod.name,
                nameHindi: prod.nameHindi,
                description: prod.description,
                price: prod.price,
                originalPrice: prod.originalPrice,
                category: { connect: { id: prod.categoryId } },
                image: prod.image,
                badge: prod.badge || null,
                badgeColor: prod.badgeColor || null,
                rating: prod.rating,
                reviewCount: prod.reviewCount,
                isVeg: prod.isVeg,
                isAvailable: prod.isAvailable,
                isFeatured: prod.isFeatured,
                isTodaySpecial: prod.isTodaySpecial,
                weightGrams: prod.weightGrams,
                allergens: prod.allergens || [],
                ingredients: prod.ingredients || null,
                shelfLifeDays: prod.shelfLifeDays,
            },
            create: {
                id: prod.id,
                slug: prod.slug,
                name: prod.name,
                nameHindi: prod.nameHindi,
                description: prod.description,
                price: prod.price,
                originalPrice: prod.originalPrice,
                category: { connect: { id: prod.categoryId } },
                image: prod.image,
                badge: prod.badge || null,
                badgeColor: prod.badgeColor || null,
                rating: prod.rating,
                reviewCount: prod.reviewCount,
                isVeg: prod.isVeg,
                isAvailable: prod.isAvailable,
                isFeatured: prod.isFeatured,
                isTodaySpecial: prod.isTodaySpecial,
                weightGrams: prod.weightGrams,
                allergens: prod.allergens || [],
                ingredients: prod.ingredients || null,
                shelfLifeDays: prod.shelfLifeDays,
            } as any, // Cast to any to bypass outdated Prisma client types in IDE
        });
    }
    console.log('Products seeded.');

    await (prisma as any).deliveryPricing.upsert({
        where: { id: 1 },
        update: {
            freeDeliveryThreshold: 499,
            reducedDeliveryThreshold: 299,
            reducedDeliveryFee: 30,
            baseDeliveryFee: 50,
        },
        create: {
            id: 1,
            freeDeliveryThreshold: 499,
            reducedDeliveryThreshold: 299,
            reducedDeliveryFee: 30,
            baseDeliveryFee: 50,
        },
    });

    console.log('Delivery pricing seeded.');

    console.log('Seeding finished successfully!');
}

main()
    .catch((e) => {
        console.error('Seeding failed:');
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
